# Generated by Django 4.2.13 on 2026-05-20 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_sessions', '0002_add_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'campaign_acts',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('setting', models.CharField(blank=True, max_length=200)),
                ('era', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('master_notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='campaigns.act')),
            ],
            options={
                'db_table': 'campaign_scenes',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('secret_info', models.TextField(blank=True)),
                ('portrait_image', models.ImageField(blank=True, null=True, upload_to='npcs/')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npcs', to='campaigns.campaign')),
                ('scenes', models.ManyToManyField(blank=True, related_name='npcs', to='campaigns.scene')),
            ],
            options={
                'db_table': 'campaign_npcs',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='act',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='campaigns.campaign'),
        ),
        migrations.CreateModel(
            name='SceneCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_cards', to='game_sessions.card')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_cards', to='campaigns.scene')),
                ('sent_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_scene_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign_scene_cards',
                'unique_together': {('scene', 'card')},
            },
        ),
    ]
