# Generated by Django 4.2.13 on 2026-08-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaignasset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='scenes',
        ),
        migrations.AddField(
            model_name='npc',
            name='age',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='npc',
            name='appearance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='npc',
            name='status',
            field=models.CharField(choices=[('alive', 'Alive'), ('dead', 'Dead'), ('missing', 'Missing'), ('suspect', 'Suspect')], default='alive', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaignasset',
            name='type',
            field=models.CharField(choices=[('document', 'Document'), ('photo', 'Photo'), ('note', 'Note'), ('map', 'Map')], max_length=20),
        ),
        migrations.DeleteModel(
            name='SceneCard',
        ),
    ]
