# Generated by Django 4.2.13 on 2026-05-20 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['id']},
        ),
    ]
