# Generated by Django 4.2.13 on 2026-05-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0004_card_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('document', 'Документ'), ('photo', 'Фото'), ('note', 'Нотатка'), ('npc', 'НПС')], default='document', max_length=20),
        ),
    ]
