# Generated by Django 4.2.13 on 2026-08-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0007_card_sketch'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('document', 'Документ'), ('photo', 'Фото'), ('note', 'Нотатка'), ('npc', 'НПС'), ('sketch', 'Ескіз'), ('map', 'Мапа'), ('pin', 'Позначка')], default='document', max_length=20),
        ),
    ]
