# Generated by Django 4.2.13 on 2026-08-03 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0009_alter_card_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='parent_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='game_sessions.card'),
        ),
    ]
