# Generated by Django 4.2.13 on 2026-05-18 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('residence', models.CharField(blank=True, max_length=200)),
                ('birthplace', models.CharField(blank=True, max_length=200)),
                ('backstory', models.TextField(blank=True)),
                ('portrait_image', models.ImageField(blank=True, null=True, upload_to='portraits/')),
                ('str_stat', models.PositiveIntegerField(default=50)),
                ('con_stat', models.PositiveIntegerField(default=50)),
                ('siz_stat', models.PositiveIntegerField(default=50)),
                ('dex_stat', models.PositiveIntegerField(default=50)),
                ('app_stat', models.PositiveIntegerField(default=50)),
                ('int_stat', models.PositiveIntegerField(default=50)),
                ('pow_stat', models.PositiveIntegerField(default=50)),
                ('edu_stat', models.PositiveIntegerField(default=50)),
                ('hp_current', models.PositiveIntegerField(default=10)),
                ('hp_max', models.PositiveIntegerField(default=10)),
                ('mp_current', models.PositiveIntegerField(default=10)),
                ('mp_max', models.PositiveIntegerField(default=10)),
                ('sanity_current', models.PositiveIntegerField(default=75)),
                ('sanity_max', models.PositiveIntegerField(default=99)),
                ('sanity_starting', models.PositiveIntegerField(default=75)),
                ('luck_current', models.PositiveIntegerField(default=60)),
                ('luck_max', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'characters',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_value', models.PositiveIntegerField(default=5)),
                ('current_value', models.PositiveIntegerField(default=5)),
                ('checked', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='characters.character')),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiceRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_type', models.CharField(max_length=10)),
                ('dice_count', models.PositiveIntegerField(default=1)),
                ('results', models.JSONField(default=list)),
                ('total', models.PositiveIntegerField(default=0)),
                ('visible_to_all', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice_rolls', to='characters.character')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.skill')),
            ],
            options={
                'db_table': 'dice_rolls',
                'ordering': ['-created_at'],
            },
        ),
    ]
